apiVersion: v2
name: external-secrets
description: External Secrets Operator for Kubernetes
type: application
version: 0.1.0
appVersion: "0.9.x"
dependencies:
  - name: external-secrets
    version: "~0.9.0"
    repository: https://charts.external-secrets.io
