apiVersion: v2
name: cert-manager
description: Certificate management for Kubernetes
type: application
version: 0.1.0
appVersion: "1.14.x"
dependencies:
  - name: cert-manager
    version: "~1.14.0"
    repository: https://charts.jetstack.io
