installCRDs: true

# For production environments:
replicaCount: 2

# Enable Prometheus metrics
prometheus:
  enabled: true
  servicemonitor:
    enabled: true

# Resources configuration
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# High availability
webhook:
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
cainjector:
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
