apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-scaling
  namespace: tenant1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-app
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated.monitoring.svc:9090
      metricName: http_requests_total
      query: sum(rate(http_requests_total{namespace="tenant1",service="example-app"}[2m]))
      threshold: '10'
