apiVersion: v2
name: vault
description: HashiCorp Vault for secrets management
type: application
version: 0.1.0
appVersion: "1.15.x"
dependencies:
  - name: vault
    version: "~0.26.0"
    repository: https://helm.releases.hashicorp.com
