apiVersion: v2
name: istio
description: Service mesh and ingress components for Kubernetes
type: application
version: 0.1.0
appVersion: "1.20.x"
dependencies:
  - name: base
    version: "~1.20.0"
    repository: https://istio-release.storage.googleapis.com/charts
    alias: istio-base
    condition: base.enabled
  - name: istiod
    version: "~1.20.0"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istiod.enabled
  - name: gateway
    version: "~1.20.0"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: gateway.enabled
