apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.12.0
    helm:
      values: |
        operator:
          replicaCount: 2
        metricsServer:
          replicaCount: 2
        serviceMonitor:
          enabled: true
        prometheus:
          metricServer:
            enabled: true
          operator:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
